/**
 * MISMO fixture definitions — used by seed-fixtures.ts + run-tests.ts.
 * IDs are deterministic so seeding is idempotent and cleanup is possible.
 */

export const FIXTURE_IDS = {
  A: "aaaaaaaa-0001-4000-8000-000000000001", // single-borrower DSCR, no REO
  B: "bbbbbbbb-0002-4000-8000-000000000002", // entity + guarantor, 4 REO
  C: "cccccccc-0003-4000-8000-000000000003", // cash-out refi, entity, 2 REO
} as const

type Fixture = {
  id: string
  label: string
  application_number: string
  application: Record<string, unknown>
  borrowers: Array<Record<string, unknown>>
  declarations: Array<Record<string, unknown>>
  liabilities: Array<Record<string, unknown>>
  assets: Array<Record<string, unknown>>
  reo_properties: Array<Record<string, unknown>>
}

const COMMON = {
  status: "submitted",
  arms_length: true,
  mortgage_type: "Conventional",
  lien_priority: "FirstLien",
  amortization_type: "Fixed",
  property_usage_type: "Investment",
  construction_method: "SiteBuilt",
  construction_status: "Existing",
  has_prepay_penalty: true,
  interest_only: false,
  balloon: false,
  credit_report_authorization_indicator: true,
  loan_term_months: 360,
  originator_first_name: "Nyalls",
  originator_last_name: "Scarlton",
  originator_nmls_individual: "TEST-NMLS-LO",
  originator_nmls_company: "TEST-NMLS-CO",
}

export const FIXTURES: Fixture[] = [
  // -------------------------------------------------------------------------
  // A — Single-borrower DSCR purchase, no REO, no entity, no coborrower
  // -------------------------------------------------------------------------
  {
    id: FIXTURE_IDS.A,
    label: "Single-borrower DSCR purchase",
    application_number: "TEST-MISMO-A",
    application: {
      ...COMMON,
      applicant_email: "fixture-a@test.preme",
      applicant_name: "Jane A Tester",
      applicant_phone: "+14155551010",
      applicant_first_name: "Jane",
      applicant_last_name: "Tester",
      applicant_dob: "1985-06-15",
      applicant_citizenship_type: "USCitizen",
      applicant_marital_status: "Unmarried",
      applicant_current_residence_basis: "Own",
      applicant_current_residence_months: 60,
      contact_address: "100 Market St",
      contact_city: "Atlanta",
      contact_state: "GA",
      contact_zip: "30303",
      loan_amount: 250000,
      note_amount: 250000,
      note_rate_percent: 7.875,
      loan_purpose: "Purchase",
      vesting_type: "Individual",
      property_address: "500 Investment Dr",
      property_city: "Atlanta",
      property_state: "GA",
      property_zip: "30309",
      property_county: "Fulton",
      property_value: 350000,
      year_built: 1998,
      gross_living_area_sqft: 1800,
      financed_unit_count: 1,
      attachment_type: "Detached",
      is_pud: false,
      current_occupancy_type: "Tenant",
      annual_property_tax: 3600,
      hazard_insurance_monthly: 120,
      hoa_monthly: 0,
      rental_gross_monthly: 2400,
      rental_net_monthly: 2280,
      rental_occupancy_pct: 95,
      lease_rent_monthly: 2400,
      lease_expiration_date: "2027-02-01",
      dscr_ratio: 1.25,
      dscr_rent_source: "Lease",
      total_mortgaged_properties_count: 1,
      credit_score_exact: 745,
    },
    borrowers: [],
    declarations: [
      {
        borrower_id: null,
        intent_to_occupy: false,
        homeowner_past_3yrs: true,
        bankruptcy: false,
        outstanding_judgments: false,
        party_to_lawsuit: false,
        presently_delinquent_federal_debt: false,
        undisclosed_borrowed_funds: false,
        undisclosed_mortgage_application: false,
        undisclosed_credit_application: false,
        undisclosed_comaker: false,
        prior_deed_in_lieu: false,
        prior_short_sale: false,
        prior_foreclosure: false,
        proposed_clean_energy_lien: false,
      },
    ],
    liabilities: [
      {
        owner_party: "Borrower",
        liability_type: "Revolving",
        account_identifier: "CC-1234",
        unpaid_balance_amount: 1500,
        monthly_payment_amount: 50,
        holder_name: "Test Bank Credit Card",
      },
    ],
    assets: [
      {
        owner_party: "Borrower",
        asset_type: "CheckingAccount",
        account_identifier: "CHK-0001",
        holder_name: "Test Bank",
        account_type: "Individual",
        cash_or_market_value_amount: 50000,
      },
    ],
    reo_properties: [],
  },

  // -------------------------------------------------------------------------
  // B — Entity-vested DSCR with guarantor + 4 REO
  // -------------------------------------------------------------------------
  {
    id: FIXTURE_IDS.B,
    label: "Entity + guarantor + 4 REO",
    application_number: "TEST-MISMO-B",
    application: {
      ...COMMON,
      applicant_email: "fixture-b@test.preme",
      applicant_name: "John B Tester",
      applicant_phone: "+14155551020",
      applicant_first_name: "John",
      applicant_last_name: "Tester",
      applicant_dob: "1978-03-22",
      applicant_citizenship_type: "USCitizen",
      applicant_marital_status: "Married",
      applicant_current_residence_basis: "Own",
      applicant_current_residence_months: 120,
      contact_address: "200 Peachtree NE",
      contact_city: "Atlanta",
      contact_state: "GA",
      contact_zip: "30309",
      loan_amount: 480000,
      note_amount: 480000,
      note_rate_percent: 8.125,
      loan_purpose: "Purchase",
      vesting_type: "Entity",
      entity_legal_name: "Tester Holdings LLC",
      entity_org_type: "LLC",
      entity_state_of_formation: "GA",
      entity_formation_date: "2020-05-01",
      entity_address: "200 Peachtree NE",
      entity_city: "Atlanta",
      entity_state: "GA",
      entity_zip: "30309",
      property_address: "777 Cashflow Ave",
      property_city: "Marietta",
      property_state: "GA",
      property_zip: "30060",
      property_county: "Cobb",
      property_value: 640000,
      year_built: 2005,
      gross_living_area_sqft: 2400,
      financed_unit_count: 2,
      attachment_type: "Detached",
      is_pud: false,
      current_occupancy_type: "Vacant",
      annual_property_tax: 7200,
      hazard_insurance_monthly: 180,
      hoa_monthly: 75,
      rental_gross_monthly: 4500,
      rental_net_monthly: 4275,
      rental_occupancy_pct: 95,
      dscr_ratio: 1.18,
      dscr_rent_source: "MarketForm1007",
      total_mortgaged_properties_count: 5,
      credit_score_exact: 760,
    },
    borrowers: [
      {
        role: "Guarantor",
        classification_type: "Primary",
        first_name: "John",
        last_name: "Tester",
        dob: "1978-03-22",
        citizenship_type: "USCitizen",
        marital_status: "Married",
        email: "fixture-b@test.preme",
        phone: "+14155551020",
        current_address: "200 Peachtree NE",
        current_city: "Atlanta",
        current_state: "GA",
        current_zip: "30309",
        residency_basis: "Own",
        residency_months: 120,
        credit_score_exact: 760,
        joint_with_primary: false,
      },
    ],
    declarations: [
      {
        borrower_id: null,
        intent_to_occupy: false,
        homeowner_past_3yrs: true,
        bankruptcy: false,
        outstanding_judgments: false,
        party_to_lawsuit: false,
        presently_delinquent_federal_debt: false,
        undisclosed_borrowed_funds: false,
        undisclosed_mortgage_application: false,
        undisclosed_credit_application: false,
        undisclosed_comaker: false,
        prior_deed_in_lieu: false,
        prior_short_sale: false,
        prior_foreclosure: false,
        proposed_clean_energy_lien: false,
      },
    ],
    liabilities: [
      {
        owner_party: "Entity",
        liability_type: "MortgageLoan",
        account_identifier: "MT-1001",
        unpaid_balance_amount: 285000,
        monthly_payment_amount: 2100,
        remaining_term_months: 312,
        holder_name: "REO-Lender-1",
        mortgage_type: "Conventional",
      },
      {
        owner_party: "Entity",
        liability_type: "MortgageLoan",
        account_identifier: "MT-1002",
        unpaid_balance_amount: 195000,
        monthly_payment_amount: 1580,
        remaining_term_months: 288,
        holder_name: "REO-Lender-2",
        mortgage_type: "Conventional",
      },
    ],
    assets: [
      {
        owner_party: "Entity",
        asset_type: "CheckingAccount",
        account_identifier: "BUS-CHK-1",
        holder_name: "Bizness Bank",
        account_type: "BusinessAccount",
        cash_or_market_value_amount: 140000,
      },
      {
        owner_party: "Borrower",
        asset_type: "RetirementFund",
        account_identifier: "401K-001",
        holder_name: "Fidelity",
        account_type: "Individual",
        cash_or_market_value_amount: 310000,
      },
    ],
    reo_properties: [
      reo("Peachtree Rental A",    "Atlanta",  "GA", "30309", 310000, 185000, 1650, 2400, 2280, 1),
      reo("Peachtree Rental B",    "Atlanta",  "GA", "30309", 265000, 152000, 1420, 2100, 1995, 1),
      reo("Decatur Duplex",        "Decatur",  "GA", "30030", 410000, 245000, 2300, 3400, 3230, 2),
      reo("Smyrna Single-Family",  "Smyrna",   "GA", "30080", 295000, 162000, 1510, 2250, 2138, 1),
    ],
  },

  // -------------------------------------------------------------------------
  // C — Cash-out refi, entity, single guarantor, 2 REO
  // -------------------------------------------------------------------------
  {
    id: FIXTURE_IDS.C,
    label: "Cash-out refi DSCR",
    application_number: "TEST-MISMO-C",
    application: {
      ...COMMON,
      applicant_email: "fixture-c@test.preme",
      applicant_name: "Pat C Tester",
      applicant_phone: "+14155551030",
      applicant_first_name: "Pat",
      applicant_last_name: "Tester",
      applicant_dob: "1982-11-05",
      applicant_citizenship_type: "USCitizen",
      applicant_marital_status: "Married",
      applicant_current_residence_basis: "Own",
      applicant_current_residence_months: 84,
      contact_address: "300 Lenox Park",
      contact_city: "Atlanta",
      contact_state: "GA",
      contact_zip: "30319",
      loan_amount: 320000,
      note_amount: 320000,
      note_rate_percent: 7.625,
      loan_purpose: "Refinance",
      vesting_type: "Entity",
      entity_legal_name: "Pat Real Estate LLC",
      entity_org_type: "LLC",
      entity_state_of_formation: "GA",
      entity_formation_date: "2022-07-15",
      entity_address: "300 Lenox Park",
      entity_city: "Atlanta",
      entity_state: "GA",
      entity_zip: "30319",
      property_address: "900 Refi Lane",
      property_city: "Roswell",
      property_state: "GA",
      property_zip: "30075",
      property_county: "Fulton",
      property_value: 470000,
      property_acquired_date: "2022-09-10",
      property_original_cost: 410000,
      property_existing_lien_amount: 245000,
      year_built: 2012,
      gross_living_area_sqft: 2150,
      financed_unit_count: 1,
      attachment_type: "Detached",
      is_pud: true,
      current_occupancy_type: "Tenant",
      annual_property_tax: 4800,
      hazard_insurance_monthly: 155,
      hoa_monthly: 110,
      property_mgmt_fee_monthly: 250,
      rental_gross_monthly: 2950,
      rental_net_monthly: 2802,
      rental_occupancy_pct: 95,
      lease_rent_monthly: 2900,
      lease_expiration_date: "2026-11-30",
      dscr_ratio: 1.15,
      dscr_rent_source: "LowerOf",
      total_mortgaged_properties_count: 3,
      credit_score_exact: 738,
    },
    borrowers: [
      {
        role: "Guarantor",
        classification_type: "Primary",
        first_name: "Pat",
        last_name: "Tester",
        dob: "1982-11-05",
        citizenship_type: "USCitizen",
        marital_status: "Married",
        email: "fixture-c@test.preme",
        phone: "+14155551030",
        current_address: "300 Lenox Park",
        current_city: "Atlanta",
        current_state: "GA",
        current_zip: "30319",
        residency_basis: "Own",
        residency_months: 84,
        credit_score_exact: 738,
        joint_with_primary: false,
      },
    ],
    declarations: [
      {
        borrower_id: null,
        intent_to_occupy: false,
        homeowner_past_3yrs: true,
        bankruptcy: false,
        outstanding_judgments: false,
        party_to_lawsuit: false,
        presently_delinquent_federal_debt: false,
        undisclosed_borrowed_funds: false,
        undisclosed_mortgage_application: false,
        undisclosed_credit_application: false,
        undisclosed_comaker: false,
        prior_deed_in_lieu: false,
        prior_short_sale: false,
        prior_foreclosure: false,
        proposed_clean_energy_lien: false,
      },
    ],
    liabilities: [
      {
        owner_party: "Entity",
        liability_type: "MortgageLoan",
        account_identifier: "EXISTING-1",
        unpaid_balance_amount: 245000,
        monthly_payment_amount: 1820,
        remaining_term_months: 276,
        holder_name: "Existing DSCR Lender",
        payoff_at_close: true,
        mortgage_type: "Conventional",
      },
    ],
    assets: [
      {
        owner_party: "Entity",
        asset_type: "CheckingAccount",
        account_identifier: "BIZ-CHK-2",
        holder_name: "LLC Bank",
        account_type: "BusinessAccount",
        cash_or_market_value_amount: 95000,
      },
    ],
    reo_properties: [
      reo("Another Rental 1", "Alpharetta", "GA", "30004", 385000, 210000, 1980, 2850, 2708, 1),
      reo("Another Rental 2", "Dunwoody",   "GA", "30338", 445000, 260000, 2325, 3200, 3040, 1),
    ],
  },
]

function reo(
  street: string,
  city: string,
  state: string,
  zip: string,
  present_market_value: number,
  lien_upb_amount: number,
  monthly_mortgage_payment: number,
  monthly_rental_income_gross: number,
  monthly_rental_income_net: number,
  unit_count: number
): Record<string, unknown> {
  return {
    is_subject: false,
    disposition_status: "HeldForInvestment",
    usage_type: "Investment",
    address_line1: street,
    city,
    state,
    postal_code: zip,
    present_market_value,
    lien_upb_amount,
    monthly_mortgage_payment,
    monthly_maintenance_expense: Math.round(monthly_rental_income_gross * 0.1),
    monthly_rental_income_gross,
    monthly_rental_income_net,
    unit_count,
  }
}
